apiVersion: v1
kind: Service
metadata:
  name: olivetti-flask-service
spec:
  type: LoadBalancer
  selector:
    app: olivetti-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
